Publish pose measured by Arduino
gtagency/buzzmobile pull request #100
Opened 2016-11-02 01:11 UTC by dacohen

2016-11-02 14:57 UTC, irapha requested changes

2016-11-02 14:57 UTC, iRapha commented on buzzmobile/drive/car_interface/src/main.cpp
> +  encoder_pub = node_handle.advertise<buzzmobile::CarPose>("measured_pose", 1000);
Can you rename to `odom_car_pose` or `measured_car_pose`?

Also do we want a queue of 1000?

2016-11-02 15:17 UTC, iRapha commented
Can you also update architecture to reflect the fact that a new message is being published? It can be an arrow leading nowhere

2016-11-03 19:08 UTC, joshuamorton approved these changes

2016-11-03 19:08 UTC, irapha approved these changes

2016-11-03 19:23 UTC, merged