Confirm 'gps_mapper' functionality and fix naming scheme across a few files.
gtagency/buzzmobile pull request #120
Opened 2016-11-09 02:20 UTC by diptodip

Closes #83.

2016-11-09 02:28 UTC, diptodip commented
Note that this leaves the great-circle distance/haversine calculation in ``bearing.py`` incorrect (not dividing by 2 where it should be) so that @joshuamorton does not get conflicts during merge, which means that still needs to be fixed at some point by someone.

2016-11-10 14:47 UTC, irapha requested changes
I believe @joshuamorton is fixing the great distance problems in https://github.com/gtagency/buzzmobile/compare/rostest.

But I think he was only fixing the issue in `calculate_distance`. Did `haversine` have problems too? If so can you fix in this PR?

2016-11-12 18:46 UTC, diptodip commented
Nah, ``haversine`` works.

2016-11-12 18:50 UTC, irapha approved these changes

2016-11-12 18:51 UTC, merged