an alternative to inputer in lisp that should work, still needs testing
gtagency/buzzmobile pull request #195
Opened 2017-03-12 08:40 UTC by chsahit

2017-03-12 08:43 UTC, diptodip commented
MY BOYYYYYYY

2017-03-12 18:38 UTC, irapha requested changes
Please also write simulation tests for this node. You will probably need to mock out stdin. Good luck

2017-03-12 18:38 UTC, iRapha commented on buzzmobile/sense/inputer/inputer.lisp
> +(defun inputer ()
can you modify the name to be more representative of what this node would be?

2017-03-12 18:38 UTC, iRapha commented on buzzmobile/sense/inputer/inputer.lisp
> +(in-package :buzzmobile)
Is this strictly necessary? Wouldn't ROS just figure out the package?

2017-03-12 18:38 UTC, iRapha commented on buzzmobile/sense/inputer/inputer.lisp
> +    (with-ros-node ("inputer")
How does lisp know that ros is a thing it can access? Where is `with-ros-node` coming from/being imported?

2017-03-12 18:38 UTC, iRapha commented on buzzmobile/sense/inputer/inputer.lisp
> +        (let ((i 0) (pub (advertise "destination" "std_msgs/String")))
Same question for `pub`, `advertise`, etc

2017-03-12 18:38 UTC, iRapha commented on buzzmobile/sense/inputer/inputer.lisp
> +            (loop-at-most-every .1
How was this this interval chosen? should it be factored out and made available to more nodes?

2017-03-12 18:38 UTC, iRapha commented on buzzmobile/sense/inputer/inputer.lisp
> +                (publish-msg pub :data (read))))))
does put take in more than just one arg? Do we need the named arg `:data`? Can't we just give `pub.publish-msg()` the `read` as an arg?

2017-03-12 18:38 UTC, iRapha commented on buzzmobile/sense/inputer/inputer.lisp
> +                (publish-msg pub :data (read))))))
Please factor out the publishing logic into its own module that can be imported everywhere

2017-03-12 18:38 UTC, iRapha commented on buzzmobile/sense/inputer/inputer.lisp
> +            (loop-at-most-every .1
~~Consider~~ factor~~ing~~ out the whole loop logic. Does lisp also do protocols? Can you write a protocol/interface for looping?

2017-03-12 18:38 UTC, iRapha commented on buzzmobile/sense/inputer/inputer.lisp
> +    (with-ros-node ("inputer")
Do you not need to node.init? what about ros.spin?

2017-03-12 18:38 UTC, iRapha commented on buzzmobile/sense/inputer/inputer.lisp
> +(defun inputer ()
This function is not being called anywhere. Please fix

2017-03-12 18:38 UTC, iRapha commented on buzzmobile/sense/inputer/inputer.lisp
> +(defun inputer ()
Can you also write tests to make sure it works?

2017-03-12 18:38 UTC, iRapha commented on buzzmobile/sense/inputer/inputer.lisp
> +            (loop-at-most-every .1
Please write an integration test for using the factored out loop protocol implementation

2017-03-12 19:56 UTC, jgkamat requested changes
Clearly needs more work before this is up to spec.

2017-03-12 19:56 UTC, jgkamat commented on buzzmobile/sense/inputer/inputer.lisp
> +(defun inputer ()
This function has no documentation attached to it. This is bad.
http://www.lispworks.com/documentation/HyperSpec/Body/m_defun.htm

Make sure to follow the documentation standards.

2017-03-12 19:56 UTC, jgkamat commented on buzzmobile/sense/inputer/inputer.lisp
> +                (publish-msg pub :data (read))))))
You are not handling any of the errors `(read)` can throw.
http://www.lispworks.com/documentation/HyperSpec/Body/f_rd_rd.htm

2017-03-12 19:56 UTC, jgkamat commented on buzzmobile/sense/inputer/inputer.lisp
> +        (let ((i 0) (pub (advertise "destination" "std_msgs/String")))
is `i` ever used anywhere? What is this?!?!?!

2017-03-12 19:56 UTC, jgkamat commented on buzzmobile/sense/inputer/inputer.lisp
> +            (loop-at-most-every .1
`.1` is a magic number. You should define it as a `+constant+`

2017-03-12 19:59 UTC, iRapha commented on buzzmobile/sense/inputer/inputer.lisp
> +            (loop-at-most-every .1
hell, go further and make it a rosparam

2017-03-12 20:51 UTC, iRapha commented
I already reviewed

2017-03-17 03:26 UTC, chsahit commented on buzzmobile/sense/inputer/inputer.lisp
> +(defun inputer ()
Actually though, the original node was also named 

> inputer

So if it's a bad name we should defs change it

2017-03-17 03:31 UTC, iRapha commented on buzzmobile/sense/inputer/inputer.lisp
> +(defun inputer ()
Yes please change it in this PR too

2017-03-28 22:28 UTC, iRapha commented
closing due to inactivity.

2017-03-28 22:28 UTC, closed without merging