Interpolation is now its own node and functions more efficiently.
gtagency/buzzmobile pull request #65
Opened 2016-10-24 13:37 UTC by diptodip

No longer storing a full image and has been split into its own node. Needs more (any) testing and probably will be changed to use parameters file.

2016-10-24 14:02 UTC, iRapha commented
For reference, this PR, when merged... Fixes #13 and #7

Can you merge `master` into your branch and fix the conflicts?

2016-10-25 00:39 UTC, irapha requested changes

2016-10-25 00:39 UTC, iRapha commented on buzzmobile/process/gps_mapper/bearing.py
> +#TODO: Don't update fix if last_fix is within epsilon of current fix.
Can you make an issue for this?

2016-10-25 00:39 UTC, iRapha commented on buzzmobile/process/gps_mapper/bearing.py
> +med_filter = MedianFilter(3)
Do we want size to be 3? Isn't 5 a more reasonable number?

2016-10-25 00:39 UTC, iRapha commented on buzzmobile/process/gps_mapper/bearing.py
> +        index = (len(self.array) - 1) // 2
What is this index? Why the `- 1`?

2016-10-25 00:39 UTC, iRapha commented on buzzmobile/process/gps_mapper/bearing.py
> +    rospy.init_node('compute_bearing', anonymous=True)
Can you change the node name to `bearing`, this method's name to `bearing_node` and move this file to `buzzmobile/bearing/bearing.py`?

2016-10-25 00:39 UTC, iRapha commented on buzzmobile/process/gps_mapper/bearing.py
> +    rospy.Subscriber('fix', NavSatFix, bearing)
`'fix'` => `'/fix'`

When we do roslaunch, all our nodes get namespaced into `/buzzmobile/`. This means that accessing messages not in the launch file (such as `nmea_navsat_driver` will not work unless we specify that we want the message coming from the root namespace (which is why we need to add `/` here).

2016-10-25 00:39 UTC, iRapha commented on buzzmobile/process/gps_mapper/gps_mapper.py
> +class Frames(object):
Don't use class for this. Instead, use a dict. For an example, see:

https://github.com/gtagency/buzzmobile/blob/c308441c251bc14262ad8c780b68129bd7a7955b/buzzmobile/sense/maps_querier/maps_querier.py#L18

There are reasons for this. One being that the `bearing` you're setting as `None` in the `__init__` is not the same as the `bearing` you're checking when doing `hasattr()`. The other being that we believe this creates a memory leak. See #62

2016-10-25 00:39 UTC, iRapha commented on buzzmobile/process/gps_mapper/gps_mapper.py
> +    rospy.Subscriber('fix', NavSatFix, set_location)
`'fix'` => `'/fix'`

See other comment

2016-10-25 00:39 UTC, iRapha commented on buzzmobile/process/gps_mapper/interpolate.py
> +    """
Can you remove main, since it's just for testing and everything is commented out?

2016-10-25 00:39 UTC, iRapha commented on buzzmobile/sense/gps/maps.py
> +    R = 6371
Are we still using maps.py? Can we delete everything in `/sense/gps`?

2016-10-25 00:39 UTC, iRapha commented on buzzmobile/process/gps_mapper/interpolate.py
> +def xwindow(points, location, angle, height=500, width=500):
Don't hardcode the `height` and `width`. Use the rosparams in `constants.xml`

2016-10-25 00:39 UTC, iRapha commented on buzzmobile/process/gps_mapper/interpolate.py
> +def window(image, location, angle, height=500, width=500):
don't hardcode height/width see other comment

2016-10-25 00:39 UTC, iRapha commented on buzzmobile/process/gps_mapper/interpolate.py
> +def normalized_points(points, height=500, width=500):
no hardcode see other comment

2016-10-25 00:39 UTC, iRapha commented on buzzmobile/process/gps_mapper/interpolate.py
> +def interpolate(points, sigma_x, sigma_y, height=500, width=500):
hardcode bad pls see other comm

2016-10-25 00:39 UTC, iRapha commented on buzzmobile/process/gps_mapper/gps_mapper.py
> +    if hasattr(frames, 'location'):
Doesn't this also need `points` to be set? Should we be checking for it here too?

2016-10-25 00:39 UTC, iRapha commented on buzzmobile/process/gps_mapper/gps_mapper.py
> +    if hasattr(frames, 'bearing'):
Doesn't this also need `points` to be set? Should we be checking for it here too?

2016-10-25 15:27 UTC, joshuamorton commented on buzzmobile/process/gps_mapper/gps_mapper.py
> +class Frames(object):
alternatively, namedtuple is an option here.

2016-10-25 22:08 UTC, diptodip commented on buzzmobile/process/gps_mapper/gps_mapper.py
> +    if hasattr(frames, 'location'):
nope

2016-10-25 22:08 UTC, diptodip commented on buzzmobile/process/gps_mapper/gps_mapper.py
> +    if hasattr(frames, 'bearing'):
nope

2016-10-25 22:08 UTC, diptodip commented on buzzmobile/process/gps_mapper/bearing.py
> +        index = (len(self.array) - 1) // 2
it's a median

2016-10-25 22:13 UTC, diptodip commented on buzzmobile/process/gps_mapper/gps_mapper.py
> +    if hasattr(frames, 'location'):
explanation: we don't need to check points

2016-10-25 22:14 UTC, diptodip commented on buzzmobile/process/gps_mapper/gps_mapper.py
> +    if hasattr(frames, 'location'):
because it gets checked in update_image()

2016-10-25 22:26 UTC, diptodip commented on buzzmobile/process/gps_mapper/interpolate.py
> +def window(image, location, angle, height=500, width=500):
these are defaults, they get called from gps_mapper.py so it will get changed to use parameters file in gps_mapper.py

2016-10-26 00:54 UTC, irapha approved these changes

2016-10-26 01:38 UTC, merged