added pylint
gtagency/buzzmobile pull request #86
Opened 2016-10-26 19:14 UTC by ruyimarone

2016-10-26 19:50 UTC, irapha requested changes
I have more comments but I have to review later.

2016-10-26 19:50 UTC, iRapha commented on .travis.yml
> +    #- sudo apt-get install pylint
What's the command for running pylint? Can you add it in the `script` section of `.travis.yml`?

2016-10-26 19:50 UTC, iRapha commented on pylintrc
> +max-line-length=100
make 80

2016-10-27 17:25 UTC, irapha commented on .travis.yml
> +    #- sudo apt-get install pylint
For reference, it's `find . -name "*.py" -exec pylint {} -rn \;`

2016-10-27 18:07 UTC, irapha requested changes
I looked over a lot of things. The one that will take the longest is making the messages that we are checking for more explicit in our file (not relying on default messages being applied)

2016-10-27 18:07 UTC, irapha commented on pylintrc
> +reports=yes
Why don't we set this to 'no' and then we don't need the command line flag `-rn`?

The running command becomes: `find . -name "*.py" -exec pylint {} \;`

2016-10-27 18:07 UTC, irapha commented on pylintrc
> +ignore=CVS
What's CVS that we're ignoring?

2016-10-27 18:07 UTC, irapha commented on pylintrc
> +disable=E1101, F0401, C0111
Instead of disabling a few messages, why don't we be explicit and say which messages we are enabling (along with a brief comment saying what that message does)?

So it would look like:

```
disable=all
enable= E1101 # checks for X
enable= F0401 # checks for Y
```

2016-10-27 18:07 UTC, irapha commented on pylintrc
> +#msg-template=
There's also a lot of unused things that we probably don't want to merge to master. I'm fine with them staying here while we go through code review because it allows discussion around unused things to happen but I'm gonna ask to remove them at some point c:

2016-10-27 18:07 UTC, irapha commented on pylintrc
> +notes=FIXME,XXX,TODO
I kind of want to enforce that `TODO`s are committed in the following format:

```
# TODO(github_username): what they need to do
```

Is there a way to do that?

2016-10-27 18:07 UTC, irapha commented on pylintrc
> +ignore-imports=no
We might want to ignore-imports. Otherwise, we might run into this issue:

https://stackoverflow.com/questions/29206482/pylint-duplicate-code-false-positive

2016-10-27 18:07 UTC, irapha commented on pylintrc
> +single-line-if-stmt=no
yes. why not?

2016-10-27 18:07 UTC, irapha commented on pylintrc
> +max-module-lines=1000
I kind of want to make this number smaller >:)

2016-10-27 18:07 UTC, irapha commented on pylintrc
> +bad-functions=map,filter,apply,input
Any reason why we shouldn't use `map` or `filter`? @joshuamorton

2016-10-27 18:07 UTC, irapha commented on pylintrc
> +# Regular expression which should only match correct module level names
change end of comment to
`(...) module-level variable names`

2016-10-27 18:07 UTC, irapha commented on pylintrc
> +disable=E1101, F0401, C0111
What are all the messages anyways?

2016-10-27 18:07 UTC, iRapha commented on pylintrc
> +max-args=5
This is gonna make @diptodip cry a little but im ok with it

2016-10-27 18:07 UTC, iRapha commented on pylintrc
> +
I also kind of want to enforce the following, but don't know if it's possible:

If there is a `rospy.init_node('a_name'` in a file...
- this line must be in a method called `a_name_node()`
- this method must be the one called by `if __name__ == '_main__': a_name_node()` (and I'd also like this `if` to be inline)
- the module name (= name of file) must be `a_name`

2016-11-02 07:31 UTC, joshuamorton commented on pylintrc
> +notes=FIXME,XXX,TODO
Nope, Google (whose style guide suggests that format) doesn't enforce it via pylint (see [their pylintrc](https://github.com/vinitkumar/googlecl/blob/master/googlecl-pylint.rc#L130))

2016-11-02 13:36 UTC, iRapha commented on pylintrc
> +notes=FIXME,XXX,TODO
But why shouldn't we?

2016-11-02 15:23 UTC, iRapha commented
LMK when you have a ready-for-review version of this.

2016-11-02 18:21 UTC, joshuamorton commented on pylintrc
> +notes=FIXME,XXX,TODO
No I'm saying that pylint isn't powerful enough to do that, so they use something else to enforce it.

2016-11-02 18:25 UTC, iRapha commented on pylintrc
> +notes=FIXME,XXX,TODO
hm okay. if we can't define custom messages then I'm ok with not having this. I just kind of wanted it to exist.

2016-11-12 20:29 UTC, iRapha commented
bumpity bump

2016-11-14 15:49 UTC, irapha requested changes

2016-11-14 15:49 UTC, iRapha commented on buzzmobile/pylintrc
> +jobs=1
Can we use more than one job? Use like 4. If it doesn't work in ci, i'll revert

2016-11-14 15:49 UTC, iRapha commented on buzzmobile/pylintrc
> +ignore-patterns=
These things in the format `bla=`. Do we need them? Can we comment them out?

2016-11-14 15:49 UTC, iRapha commented on buzzmobile/pylintrc
> +#disable=print-statement,parameter-unpacking,unpacking-in-except,old-raise-syntax,backtick,long-suffix,old-ne-operator,old-octal-literal,import-star-module-level,raw-checker-failed,bad-inline-option,
do we need this ugly commented out line?

2016-11-14 15:49 UTC, iRapha commented on buzzmobile/pylintrc
> +output-format=text
change to colorized?

2016-11-14 15:49 UTC, iRapha commented on buzzmobile/pylintrc
> +callbacks=cb_,_cb
add `cb` to this

2016-11-14 15:49 UTC, iRapha commented on buzzmobile/todo.py
> +# pylint: disable=W0511
this (and in general the comment above) is incorrect, no?

2016-11-15 23:37 UTC, joshuamorton approved these changes

2016-11-15 23:37 UTC, irapha approved these changes

2016-11-15 23:37 UTC, merged